// <auto-generated />
namespace EnlaceNoivas.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCountVoteToCouple : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCountVoteToCouple));
        
        string IMigrationMetadata.Id
        {
            get { return "201311041653125_AddCountVoteToCouple"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
