// <auto-generated />
namespace EnlaceNoivas.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class alteridnameinEmailList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteridnameinEmailList));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021741453_alteridnameinEmailList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
