// <auto-generated />
namespace EnlaceNoivas.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removePhoneTableAndAddPhonesFieldsToProvider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removePhoneTableAndAddPhonesFieldsToProvider));
        
        string IMigrationMetadata.Id
        {
            get { return "201309171434524_removePhoneTableAndAddPhonesFieldsToProvider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
