// <auto-generated />
namespace EnlaceNoivas.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IDontKnow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IDontKnow));
        
        string IMigrationMetadata.Id
        {
            get { return "201309231502058_IDontKnow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
